<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="MAIN" Id="{cce30028-973b-43e0-9926-98c587a2f51b}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR

END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="458" Count="0" />
      <LineId Id="418" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>