<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="POU" Id="{3fc62ccb-fe41-4ede-9fd5-674cbea254bf}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU
VAR
	btest: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[btest := TRUE;
]]></ST>
    </Implementation>
    <LineIds Name="POU">
      <LineId Id="5" Count="1" />
    </LineIds>
  </POU>
</TcPlcObject>